version: '3'

services:
  worker:
    build: .
    ports:
      - "5000:5000"
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    # Cuando tengas el servicio de tu compañero, puedes agregarlo aquí
    # networks:
    #   - scraper_network

# networks:
#   scraper_network:
#     # Esto permitiría conectarse a la red de tu compañero
#     # external: true
#     # name: nombre_de_la_red_de_tu_companero